### ISSUE TITLE
fix resnet50 segfaults on navi3x

### ISSUE THREAD

**Issue by manupak** [ROCm/AMDMIGraphX#2243]
```
./bin/migraphx-driver run /mnt/nas_share/migraphx/models/mlperf/resnet50_v1.onnx
```

results in a segfault on the trunk (commit : https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/commit/434a06cf36b7518a446f03975a4d51dc4b374766)

Steps to reproduce on [aus-navi3x-13.amd.com](http://rocmhead:8080/computer/aus-navi3x-13.amd.com) :
```
docker run -itd --device=/dev/kfd --device=/dev/dri  -v /nas/models:/models --group-add video --hostname migraphx --name migraphx rocm/mlir-migraphx-ci:latest 
docker exec migraphx bash -c "git clone -b develop https://github.com/ROCmSoftwarePlatform/AMDMIGraphX.git"
docker exec -w /AMDMIGraphX migraphx bash -c "cmake . -G \"Unix Makefiles\" -B build -DMIGRAPHX_ENABLE_MLIR=On -DCMAKE_PREFIX_PATH=/MIGraphXDeps -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++"
docker exec -w /AMDMIGraphX/build migraphx bash -c "make -j driver"
docker exec migraphx /AMDMIGraphX/build/bin/migraphx-driver run/perf models/mlperf/resnet50_v1.onnx
```

Initial investigation suggests via rocgdb suggests something to do with argmax op
```
#5  0x00007fffbff91abc in hipLaunchKernel () from /opt/rocm-5.6.0/lib/libamdhip64.so.5
#6  0x00007fffba29bbb1 in _ZN8migraphx13version_2_7_03gpu6device23__device_stub__launcherIZZNS2_9gs_launchEP12ihipStream_tjjENKUlT_E_clIZZNS2_6arg_opINS2_9argmax_opEEEvS6_S5_RKNS0_8argumentESD_lENKUlS6_T0_T1_E_clINS2_15hip_tensor_viewIfLj2EEENS2_9hip_shapeILj2EEESL_EEDaS6_SE_SF_EUlS6_SE_E_EEDaS6_EUlS6_E_EEvS6_ () from /home/mkarunar/work/AMDMIGraphX/build/lib/libmigraphx_device.so.2
#7  0x00007fffba29b553 in _ZZN8migraphx13version_2_7_03gpu6device6launchEP12ihipStream_tjjENKUlT_E_clIZZNS2_9gs_launchES4_jjENKUlS5_E_clIZZNS2_6arg_opINS2_9argmax_opEEEvS5_S4_RKNS0_8argumentESE_lENKUlS5_T0_T1_E_clINS2_15hip_tensor_viewIfLj2EEENS2_9hip_shapeILj2EEESM_EEDaS5_SF_SG_EUlS5_SF_E_EEDaS5_EUlS5_E_EEDaS5_ (this=0x7fffffffb958, f=...)
    at /home/mkarunar/work/AMDMIGraphX/src/targets/gpu/device/include/migraphx/gpu/device/launch.hpp:85
#8  0x00007fffba29b3eb in migraphx::version_2_7_0::gpu::device::gs_launch(ihipStream_t*, unsigned int, unsigned int)::{lambda(auto:1)#1}::operator()<migraphx::version_2_7_0::gpu::device::arg_op<migraphx::version_2_7_0::gpu::device::argmax_op>(migraphx::version_2_7_0::gpu::device::argmax_op, ihipStream_t*, migraphx::version_2_7_0::argument const&, migraphx::version_2_7_0::argument const&, long)::{lambda(auto:1, auto:2, auto:3)#1}::operator()<migraphx::version_2_7_0::gpu::device::hip_tensor_view<float, 2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u> >(migraphx::version_2_7_0::gpu::device::hip_tensor_view<float, 2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u>) const::{lambda(auto:1, auto:2)#1}>(migraphx::version_2_7_0::gpu::device::arg_op<migraphx::version_2_7_0::gpu::device::argmax_op>(migraphx::version_2_7_0::gpu::device::argmax_op, ihipStream_t*, migraphx::version_2_7_0::argument const&, migraphx::version_2_7_0::argument const&, long)::{lambda(auto:1, auto:2, auto:3)#1}::operator()<migraphx::version_2_7_0::gpu::device::hip_tensor_view<float, 2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u> >(migraphx::version_2_7_0::gpu::device::hip_tensor_view<float, 2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u>) const::{lambda(auto:1, auto:2)#1}) const (
    this=0x7fffffffbb10, f=...) at /home/mkarunar/work/AMDMIGraphX/src/targets/gpu/device/include/migraphx/gpu/device/launch.hpp:121
#9  0x00007fffba29b2c5 in migraphx::version_2_7_0::gpu::device::arg_op<migraphx::version_2_7_0::gpu::device::argmax_op>(migraphx::version_2_7_0::gpu::device::argmax_op, ihipStream_t*, migraphx::version_2_7_0::argument const&, migraphx::version_2_7_0::argument const&, long)::{lambda(auto:1, auto:2, auto:3)#1}::operator()<migraphx::version_2_7_0::gpu::device::hip_tensor_view<float, 2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u> >(migraphx::version_2_7_0::gpu::device::hip_tensor_view<float, 2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u>, migraphx::version_2_7_0::gpu::device::hip_shape<2u>) const (this=0x7fffffffc510, input=..., arg_s=..., batch_s=...) at /home/mkarunar/work/AMDMIGraphX/src/targets/gpu/include/migraphx/gpu/device/arg_op.hpp:110
```

# DoD
* resnet50 can be run on navi3x again

**Comment by manupak** [comment]
cc: @jerryyin @ravil-mobile

**Comment by manupak** [comment]
This only happens with the model in mlse-nas though and does not happen with https://github.com/onnx/models/raw/ba629906dd91872def671e70177c5544e0ea9e02/vision/classification/resnet/model/resnet50-v1-7.onnx

**Comment by causten** [comment]
Those models are different, the one on mlse-nas is the MLPerf version.  Both should work but I would consider the MLPerf version to be the Tier1 model. 
![image](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/assets/7440191/a023945b-813c-4ae3-ac26-4015cfa3c7c0)

**Comment by manupak** [comment]
Alright then.

We(rocMLIR) are omitting mlperf/resnet from our testing for now until MIGraphX fixes this issue that blocks us from running it.

**Comment by manupak** [comment]
(Note this happens without rocMLIR)

**Comment by causten** [comment]
Before I start the investigation can you change your docker exec first.  You need to add the GPU target and remove the compiler target

docker exec -w /AMDMIGraphX migraphx bash -c "cmake . -G \"Unix Makefiles\" -B build -DMIGRAPHX_ENABLE_MLIR=On -DCMAKE_PREFIX_PATH=/MIGraphXDeps -DGPU_TARGETS=\"gfx1100;gfx1101\""

**Comment by manupak** [comment]
I tried this instead within the container (hope that is equivalent ?) : 
```
cmake -G Ninja .. -DCMAKE_PREFIX_PATH=/MIGraphXDeps -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++ -DCMAKE_BUILD_TYPE=debug -DGPU_TARGETS="gfx1100;gfx1101"
ninja driver
./bin/migraphx-driver run /mnt/nas_share/migraphx/models/mlperf/resnet50_v1.onnx 
Compiling ... 
Reading: /mnt/nas_share/migraphx/models/mlperf/resnet50_v1.onnx
terminate called after throwing an instance of 'migraphx::version_2_7_0::exception'
  what():  /home/mkarunar/work/AMDMIGraphX/src/targets/gpu/device_name.cpp:39: get_device_id: No device
Aborted (core dumped)
```
